version: '3.8'

networks:
  stack-track:
    name: stack-track

services:
  stack-track-core:
    container_name: stack-track-core
    image: localhost:3002/sam/stack-track-core:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:9090"  # Maps host port 90 to container port 8080
    restart: unless-stopped 
    networks:
      - stack-track