name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Add gitea hostname mapping
        run: |
          echo "10.21.0.26 gitea_server_1" | sudo tee -a /etc/hosts
          echo "Added gitea_server_1 to hosts file:"
          grep gitea_server_1 /etc/hosts
          echo "Testing connection:"
          curl -s http://gitea_server_1:8085/api/v1/version

      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./gradlew test

      - name: Run integration tests
        run: ./gradlew integrationTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/