name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # The artifact uploader uses the ACTIONS_RESULTS_URL environment variable for the upload URL
      # For some reason this ends up being umbrel.local on an umbrel. This script maps
      # umbrel.local to the gitea server
      # https://github.com/actions/toolkit/blob/f31c2921c1228a97be08cdb38b919a83077354d9/packages/artifact/src/internal/shared/config.ts
      - name: Test connection and add host mapping if necessary
        run: |
          echo "Testing initial connection to Gitea..."
          if curl -s --connect-timeout 10 --max-time 30 http://gitea_server_1:8085/api/v1/version; then
            echo "✅ Connection to gitea_server_1 successful - no gitea host mapping needed for gitea_server_1"
            echo "Mapping umbrel.local to gitea_server_1 IP for actions/upload-artifact@v3..."
          
            # Get the IP of gitea_server_1 first
            GITEA_IP=$(getent hosts gitea_server_1 | awk '{ print $1 }')
            echo "$GITEA_IP umbrel.local" | sudo tee -a /etc/hosts
          
            echo "Added hostname mappings:"
            grep -E "(umbrel.local)" /etc/hosts
            echo "Testing connection again after adding mappings..."
          
            if curl -s --connect-timeout 10 --max-time 30 http://umbrel.local:8085/api/v1/version; then
              echo "✅ Connection to umbrel.local successful after adding hostname mappings"
            else
              echo "❌ Connection to umbrel.local still failing after hostname mappings - check network/firewall"
              exit 1
            fi
          else
            echo "❌ Connection to gitea_server_1 failed - Make sure the gitea runner and child workflow runner are on the same network as gitea"
            echo "The default network for all apps on umbrel is umbrel_main_network"
            exit 1
          fi

      - name: Debug environment variables
        run: |
          echo "=== All Environment Variables ==="
          env | sort
          echo ""
          echo "=== Looking for umbrel/artifact related vars ==="
          env | grep -i -E "(umbrel|artifact|github|gitea|upload)"

      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./gradlew test

      - name: Run integration tests
        run: ./gradlew integrationTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/